export const AuthConstants = {
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILE: 'LOGIN_FAILE',

    GET_VERIFY_CODE_REQUEST: 'GET_VERIFY_CODE_REQUEST',
    GET_VERIFY_CODE_SUCCESS: 'GET_VERIFY_CODE_SUCCESS',
    GET_VERIFY_CODE_FAILE: 'GET_VERIFY_CODE_FAILE',
    
}