export const PostConstant = {
    CHANGE_LIKE_REQUEST: 'CHANGE_LIKE_REQUEST',
    CHANGE_LIKE_SUCCESS: 'CHANGE_LIKE_SUCCESS',
    CHANGE_LIKE_FAILE: 'CHANGE_LIKE_FAILE',

    UN_LIKE_REQUEST: 'UN_LIKE_REQUEST',
    UN_LIKE_SUCCESS: 'UN_LIKE_SUCCESS',
    UN_LIKE_FAILE: 'UN_LIKE_FAILE',

    CREATE_POST_REQUEST: 'CREATE_POST_REQUEST',
    CREATE_POST_SUCCESS: 'CREATE_POST_SUCCESS',
    CREATE_POST_FAILE: 'CREATE_POST_FAILE',

}