export const PostConstant = {
    CHANGE_LIKE_REQUEST: 'CHANGE_LIKE_REQUEST',
    CHANGE_LIKE_SUCCESS: 'CHANGE_LIKE_SUCCESS',
    CHANGE_LIKE_FAILE: 'CHANGE_LIKE_FAILE',

    UN_LIKE_REQUEST: 'UN_LIKE_REQUEST',
    UN_LIKE_SUCCESS: 'UN_LIKE_SUCCESS',
    UN_LIKE_FAILE: 'UN_LIKE_FAILE',

    GET_COMMENT_POST_REQUEST: 'GET_COMMENT_POST_REQUEST',
    GET_COMMENT_POST_SUCCESS: 'GET_COMMENT_POST_SUCCESS',
    GET_COMMENT_POST_FAILE: 'GET_COMMENT_POST_FAILE',

    ADD_COMMENT_POST_REQUEST: 'ADD_COMMENT_POST_REQUEST',
    ADD_COMMENT_POST_SUCCESS: 'ADD_COMMENT_POST_SUCCESS',
    ADD_COMMENT_POST_FAILE: 'ADD_COMMENT_POST_FAILE',

}