export const NotificationConstant = {


    GET_NOTI_REQUEST: 'GET_NOTI_REQUEST',
    GET_NOTI_SUCCESS: 'GET_NOTI_SUCCESS',
    GET_NOTI_FAILE: 'GET_NOTI_FAILE',

    EDIT_NOTI_REQUEST: 'EDIT_NOTI_REQUEST',
    EDIT_NOTI_SUCCESS: 'EDIT_NOTI_SUCCESS',
    EDIT_NOTI_FAILE: 'EDIT_NOTI_FAILE',

    DELETE_NOTI_REQUEST: 'DELETE_NOTI_REQUEST',
    DELETE_NOTI_SUCCESS: 'DELETE_NOTI_SUCCESS',
    DELETE_NOTI_FAILE: 'DELETE_NOTI_FAILE',

}